--
-- PostgreSQL database dump
--

\restrict LKqscOgNyUwy3Z5T2h3EBTNBwbaLlL3jF46AYGFiHdoCKrfArzS3roMoGLLQsWN

-- Dumped from database version 16.14 (Homebrew)
-- Dumped by pg_dump version 16.14 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: games; Type: TABLE; Schema: public; Owner: djechipare
--

CREATE TABLE public.games (
    id bigint NOT NULL,
    away_score integer,
    date date,
    home_score integer,
    away_team_id bigint,
    home_team_id bigint
);


ALTER TABLE public.games OWNER TO djechipare;

--
-- Name: games_id_seq; Type: SEQUENCE; Schema: public; Owner: djechipare
--

ALTER TABLE public.games ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.games_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ingestion_runs; Type: TABLE; Schema: public; Owner: djechipare
--

CREATE TABLE public.ingestion_runs (
    id bigint NOT NULL,
    finished_at timestamp(6) without time zone,
    games_processed integer,
    started_at timestamp(6) without time zone,
    status character varying(255)
);


ALTER TABLE public.ingestion_runs OWNER TO djechipare;

--
-- Name: ingestion_runs_id_seq; Type: SEQUENCE; Schema: public; Owner: djechipare
--

ALTER TABLE public.ingestion_runs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ingestion_runs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: player_ratings; Type: TABLE; Schema: public; Owner: djechipare
--

CREATE TABLE public.player_ratings (
    id bigint NOT NULL,
    date date,
    player_id bigint,
    def_rating double precision NOT NULL,
    off_rating double precision NOT NULL,
    ovr_rating double precision NOT NULL
);


ALTER TABLE public.player_ratings OWNER TO djechipare;

--
-- Name: player_ratings_id_seq; Type: SEQUENCE; Schema: public; Owner: djechipare
--

ALTER TABLE public.player_ratings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.player_ratings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: player_stats; Type: TABLE; Schema: public; Owner: djechipare
--

CREATE TABLE public.player_stats (
    id bigint NOT NULL,
    assists integer,
    blocks integer,
    def_rebs integer,
    fg_atmpt integer,
    fg_made integer,
    off_rebs integer,
    points integer,
    steals integer,
    three_ptrs_atmpt integer,
    three_ptrs_made integer,
    turnovers integer,
    player_id bigint
);


ALTER TABLE public.player_stats OWNER TO djechipare;

--
-- Name: player_stats_id_seq; Type: SEQUENCE; Schema: public; Owner: djechipare
--

ALTER TABLE public.player_stats ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.player_stats_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: players; Type: TABLE; Schema: public; Owner: djechipare
--

CREATE TABLE public.players (
    id bigint NOT NULL,
    name character varying(255),
    pos character varying(255),
    team character varying(255)
);


ALTER TABLE public.players OWNER TO djechipare;

--
-- Name: players_id_seq; Type: SEQUENCE; Schema: public; Owner: djechipare
--

ALTER TABLE public.players ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.players_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teams; Type: TABLE; Schema: public; Owner: djechipare
--

CREATE TABLE public.teams (
    id bigint NOT NULL,
    name character varying(255)
);


ALTER TABLE public.teams OWNER TO djechipare;

--
-- Name: teams_id_seq; Type: SEQUENCE; Schema: public; Owner: djechipare
--

ALTER TABLE public.teams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teams_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: games games_pkey; Type: CONSTRAINT; Schema: public; Owner: djechipare
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT games_pkey PRIMARY KEY (id);


--
-- Name: ingestion_runs ingestion_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: djechipare
--

ALTER TABLE ONLY public.ingestion_runs
    ADD CONSTRAINT ingestion_runs_pkey PRIMARY KEY (id);


--
-- Name: player_ratings player_ratings_pkey; Type: CONSTRAINT; Schema: public; Owner: djechipare
--

ALTER TABLE ONLY public.player_ratings
    ADD CONSTRAINT player_ratings_pkey PRIMARY KEY (id);


--
-- Name: player_stats player_stats_pkey; Type: CONSTRAINT; Schema: public; Owner: djechipare
--

ALTER TABLE ONLY public.player_stats
    ADD CONSTRAINT player_stats_pkey PRIMARY KEY (id);


--
-- Name: players players_pkey; Type: CONSTRAINT; Schema: public; Owner: djechipare
--

ALTER TABLE ONLY public.players
    ADD CONSTRAINT players_pkey PRIMARY KEY (id);


--
-- Name: teams teams_pkey; Type: CONSTRAINT; Schema: public; Owner: djechipare
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_pkey PRIMARY KEY (id);


--
-- Name: player_ratings fk72x5p7e7tmgpirkiaqa8bjhre; Type: FK CONSTRAINT; Schema: public; Owner: djechipare
--

ALTER TABLE ONLY public.player_ratings
    ADD CONSTRAINT fk72x5p7e7tmgpirkiaqa8bjhre FOREIGN KEY (player_id) REFERENCES public.players(id);


--
-- Name: player_stats fkjosriw9csh9ns7gcnsrdnik57; Type: FK CONSTRAINT; Schema: public; Owner: djechipare
--

ALTER TABLE ONLY public.player_stats
    ADD CONSTRAINT fkjosriw9csh9ns7gcnsrdnik57 FOREIGN KEY (player_id) REFERENCES public.players(id);


--
-- Name: games fkm58kfr0wpwqw4gbyan1wt4ohc; Type: FK CONSTRAINT; Schema: public; Owner: djechipare
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT fkm58kfr0wpwqw4gbyan1wt4ohc FOREIGN KEY (home_team_id) REFERENCES public.teams(id);


--
-- Name: games fksxy8nadhptuk96oduoogs8p2c; Type: FK CONSTRAINT; Schema: public; Owner: djechipare
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT fksxy8nadhptuk96oduoogs8p2c FOREIGN KEY (away_team_id) REFERENCES public.teams(id);


--
-- PostgreSQL database dump complete
--

\unrestrict LKqscOgNyUwy3Z5T2h3EBTNBwbaLlL3jF46AYGFiHdoCKrfArzS3roMoGLLQsWN

